#!/usr/local/cpanel/3rdparty/bin/perl
# cpanel - find-latest-version                  Copyright(c) 2019 cPanel, L.L.C.
#                                                           All rights Reserved.
# copyright@cpanel.net                                         http://cpanel.net
# This code is subject to the cPanel license. Unauthorized copying is prohibited

package ea_repo_name_goes_here::find_latest_version;

use strict;
use warnings;

use Cpanel::JSON::XS;

use lib "../ea-tools/lib/ea4_tool";    # assumes ea-tools is checked out next to this repo
use ea4_tool::util ();

ea4_tool::util::find_latest_version( \&_get_required, \&_add_sum ) if !caller();

###############
#### helpers ##
###############

sub _get_required {
    my ($http) = @_;

    my ( $version, $url, $name );

    my $res = $http->get("https://api.github.com/repos/phalcon/cphalcon/tags");

    my $tag_refs = Cpanel::JSON::Load( $res->content );
    my $tag;

    foreach my $tag_ref ( @{$tag_refs} ) {

        # ignore release candidates, alpha, and beta releases
        next if ( $tag_ref->{name} =~ m{-(?:(?:rc)|(?:beta)|(?:alpha))} );

        if ( !defined $tag ) {
            $tag = $tag_ref;
            next;
        }

        if ( $tag_ref->{name} gt $tag->{name} ) {
            $tag = $tag_ref;
            next;
        }
    }

    die "Cannot find latest version" if !defined $tag;

    my $sha = substr( $tag->{'commit'}->{'sha'}, 0, 7 );

    $version = $tag->{'name'};
    $name    = "phalcon-cphalcon-$version-0-g$sha.tar.gz";
    $url     = $tag->{'tarball_url'};

    $version =~ s/^v//;

    return ( $version, $url, $name );
}

sub _add_sum {
    my ( $http, $hr ) = @_;

    # I could not find a way to get the sum

    return;
}

__END__

=encoding utf-8

=head1 README

This is a Github project.  The latest version is listed as a tag in the project.

